# Generated by Django 4.2.1 on 2024-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
